### ISSUE TITLE
init method stub in ETHConnectorGenerator.js

### ISSUE THREAD

**Issue by Lsquared13** [tiholic/eximchain-eth-contract-codegen#1]
In the file `ETHConnectorGenerator.js`, there is an init method stub that looks as follows:
```javascript
    /**
     * @function
     * @instance
     * @description Creates license, info objects and also openAPI instance
     * */
    init() {
        //TODO stub
    }
```

There is an `init` method in `OpenAPIGenerator.js` as well that is not a stub, and it seems possible that the stub in `ETHConnectorGenerator.js` was left there by accident.

- If the method `ETHConnectorGenerator.init` is unused and unnecessary, please delete it.
- If it is necessary but there is justification for it being a stub, please justify in the comment instead of just saying `TODO`.
- If it needs to be implemented, please implement it.

**Comment by tiholic** [comment]
@Lsquared13 removed `ETHConnectorGenerator.init` method
