### ISSUE TITLE
Documentation and Style consistency nit

### ISSUE THREAD

**Issue by Lsquared13** [tiholic/eximchain-eth-contract-codegen#2]
In OpenAPIGenerator.js there is the following method:

```javascript
    /**
     * @function
     * @param {Error} err
     * @param {String} method_name
     * @description
     * reads the error instance and message string and creates an eth error and throws it.
     * */
    _handleError(err, method_name){
        "use strict";
        console.log( `failed to execute ${method_name}... ${err}` );
        throw new ETHError( " Error Occurred!!! " );
    }
```

The doc string does not contain `@private` like the method `_createCallParams`, but the naming convention of starting the name with `_` seems to suggest it is a private method.  Please either:

- Add `@private` to the doc string for `_handleError`
- Justify why `@private` does not belong in the doc string for `_handleError`

**Comment by tiholic** [comment]
@Lsquared13 Thanks for pointing out. Updated the doc string. BTW, this method belongs to `GenericETHConnector.js`.
